---
# https://rancher.com/docs/k3s/latest/en/installation/install-options/agent-config/
# https://github.com/PyratLabs/ansible-role-k3s#agent-worker-configuration

# Don't define the host as control plane nodes
k3s_control_node: false

# k3s settings for all worker nodes
k3s_agent:
  node-ip: "{{ ansible_host }},{{ ansible_default_ipv6.address }}"
  #node-ip: "{{ ansible_default_ipv6.address }}"
  #node-ip: "{{ ansible_default_ipv6.address }},{{ ansible_host }}"
  kubelet-arg:
     # https://github.com/k3s-io/k3s/issues/1264
    - "node-status-update-frequency=4s"
