---
roles:
  - src: xanmanning.k3s
    version: v3.6.1
collections:
  - name: community.docker
    version: 5.0.0
  - name: community.general
    version: 11.4.1
  - name: community.kubernetes
    version: 2.0.1
  - name: community.sops
    version: 2.2.7
