---
roles:
  - src: xanmanning.k3s
    version: v3.4.2
collections:
  - name: community.docker
    version: 3.4.8
  - name: community.general
    version: 6.6.2
  - name: community.kubernetes
    version: 2.0.1
  - name: community.sops
    version: 1.6.2
