---
roles:
  - src: xanmanning.k3s
    version: v3.1.0
collections:
  - name: community.docker
    version: 2.2.0
  - name: community.general
    version: 4.4.0
  - name: community.kubernetes
    version: 2.0.1
  - name: community.sops
    version: 1.2.0
