---
roles:
  - src: xanmanning.k3s
    version: v3.6.2
collections:
  - name: community.docker
    version: 5.0.5
  - name: community.general
    version: 12.2.0
  - name: community.kubernetes
    version: 2.0.1
  - name: community.sops
    version: 2.2.7
