---
roles:
  - src: xanmanning.k3s
    version: v3.4.4
collections:
  - name: community.docker
    version: 4.3.0
  - name: community.general
    version: 10.1.0
  - name: community.kubernetes
    version: 2.0.1
  - name: community.sops
    version: 2.0.1
