---
roles:
  - src: xanmanning.k3s
    version: v3.2.0
collections:
  - name: community.docker
    version: 3.0.2
  - name: community.general
    version: 5.4.0
  - name: community.kubernetes
    version: 2.0.1
  - name: community.sops
    version: 1.2.3
