---
apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: netshoot-iot-static
  namespace: networking
spec:
  config: '{
      "cniVersion": "0.3.1",
      "type": "macvlan",
      "master": "eno1.50",
      "mode": "bridge",
      "ipam": {
        "type": "static",
        "addresses": [
           {
             "address": "10.0.50.40/24"
           }
         ]
      }
    }'
