---
kubernetes:
  children:
    master:
      hosts:
        k8s-master1:
          ansible_host: 10.0.105.10
      vars:
        ansible_user: ubuntu
        k3s_become: true
    worker:
      hosts:
        k8s-master1:
          ansible_host: 10.0.105.10
          k3s_become: true
        k8s-worker5:
          ansible_host: 10.0.105.15
          k3s_become: true
        k8s-worker7:
          ansible_host: 10.0.105.20
          k3s_become: true
        k8s-worker-amd64-0:
          ansible_host: 10.0.105.14
          k3s_become: true
          ansible_user: sm
        k8s-worker-amd64-2:
          ansible_host: 10.0.105.18
          k3s_become: true
          ansible_user: sm
        k8s-worker-amd64-3:
          ansible_host: 10.0.105.19
          k3s_become: true
          ansible_user: sm
      vars:
        ansible_user: ubuntu
        k3s_become: true

#router:
#  hosts:
#    gateway:
#      ansible_host: 192.168.2.1
#      ansible_user: sm
