---
kubernetes:
  children:
    master:
      hosts:
        m1:
          ansible_host: 10.0.105.34
      vars:
        ansible_user: sm
        k3s_become: true
    worker:
      hosts:
      #  w1:
      #    ansible_host: 10.0.105.10
        w2:
          ansible_host: 10.0.105.15
        w7:
          ansible_host: 10.0.105.20
      #  w-amd-0:
      #    ansible_host: 10.0.105.30
      #    ansible_user: sm
        w-amd-storage-1:
          ansible_host: 10.0.105.43
          ansible_user: sm
        w-amd-3:
          ansible_host: 10.0.105.19
          ansible_user: sm
        w-amd-2:
          ansible_host: 10.0.105.33
          ansible_user: sm
      vars:
        ansible_user: ubuntu
        k3s_become: true

#router:
#  hosts:
#    gateway:
#      ansible_host: 192.168.2.1
#      ansible_user: sm
