apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - assistant/ks.yaml
  - esphome/ks.yaml
  - grocy/ks.yaml
  - mosquitto/ks.yaml
  - zigbee2mqtt/ks.yaml
  - node-red/ks.yaml
  - ns.yaml
