apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: postgres16-vector
  namespace: flux-system
spec:
  dependsOn:
    - name: cnpg-operator
  path: ./k8s/media/apps/databases/cloudnative-pg/cluster-vectors
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  interval: 30m
  timeout: 5m