---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: monitoring-loki
  namespace: flux-system
spec:
  path: ./cluster/apps/monitoring/loki/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: cluster
  healthChecks:
    - apiVersion: helm.toolkit.fluxcd.io/v2beta1
      kind: HelmRelease
      name: loki
      namespace: monitoring
  interval: 30m
  retryInterval: 2m
  timeout: 1m
