apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ns.yaml
  - redis/ks.yaml
  - cloudnative-pg/ks.yaml
  - cloudnative-pg/ks-cluster.yaml
  - pgadmin/ks.yaml
  - cockroachdb/ks.yaml
