---
# yaml-language-server: $schema=https://kubernetes-schemas.trux.dev/helmrepository_v1beta2.json
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: cert-manager-webhook-powerdns-charts
  namespace: flux-system
spec:
  interval: 30m
  url: https://lordofsystem.github.io/cert-manager-webhook-powerdns
  timeout: 3m
