---
# yaml-language-server: $schema=https://kubernetes-schemas.trux.dev/helmrepository_v1beta2.json
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: falco-security-charts
  namespace: flux-system
spec:
  interval: 15m
  url: https://falcosecurity.github.io/charts
  timeout: 3m
