---
# yaml-language-server: $schema=https://kubernetes-schemas.trux.dev/helmrepository_v1beta2.json
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: k8s-at-home-charts
  namespace: flux-system
spec:
  interval: 15m
  url: https://k8s-at-home.com/charts/
  timeout: 3m
