---
# yaml-language-server: $schema=https://kubernetes-schemas.trux.dev/helmrepository_v1beta2.json
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: piraeus-charts
  namespace: flux-system
spec:
  interval: 12h
  url: https://piraeus.io/helm-charts/
  timeout: 3m
