---
# yaml-language-server: $schema=https://kubernetes-schemas.trux.dev/helmrepository_v1beta2.json
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: teampiped
  namespace: flux-system
spec:
  interval: 15m
  url: https://helm.piped.video
  timeout: 3m
