---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - changedetector/ks.yaml
#  - dendrite/ks.yaml
  - epic-freegames/ks.yaml
  - immich/ks.yaml
  - theme-park/ks.yaml
  - smtp-relay/ks.yaml
