---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: eck-operator
  namespace: search
spec:
  releaseName: eck-operator
  interval: 1h
  chart:
    spec:
      chart: eck-operator
      version: 2.8.0
      sourceRef:
        kind: HelmRepository
        name: elastic-charts
        namespace: flux-system
      interval: 1h
  install:
    createNamespace: true
  upgrade:
    crds: CreateReplace
  values:
    config:
      logVerbosity: "-1"
