---
apiVersion: externaldns.k8s.io/v1alpha1
kind: DNSEndpoint
metadata:
  name: cloudflared
  namespace: networking
  annotations:
    external-dns.alpha.kubernetes.io/target: "ingress-cf.skylab.fi"
spec:
  endpoints:
    - dnsName: "ingress-cf.skylab.fi"
      recordType: CNAME
      targets: ["${SECRET_CLOUDFLARE_TUNNEL_ID}.cfargotunnel.com"]