---
apiVersion: v1
kind: ConfigMap
metadata:
  name: immich-dev-configmap
  namespace: default
data:
  DB_PORT: "5432"
  DISABLE_REVERSE_GEOCODING: "true"
  ENABLE_MAPBOX: "false"
  LOG_LEVEL: verbose
  NODE_ENV: "development"
  REDIS_PORT: "6379"
  REDIS_DBINDEX: "0"
  PUBLIC_IMMICH_SERVER_URL: http://immich-dev-server.default.svc.cluster.local:3001
  IMMICH_WEB_URL: http://immich-dev-web.default.svc.cluster.local:3000
  IMMICH_SERVER_URL: http://immich-dev-server.default.svc.cluster.local:3001
  IMMICH_MACHINE_LEARNING_URL: http://immich-dev-machine-learning.default.svc.cluster.local:3003
