apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./ns.yaml
#  - ./factorio/ks.yaml
#  - ./satisfactory/ks.yaml
#   - ./minecraft/ks.yaml # Doesn't work, DNS issues for the moment.
