---
- include: locale.yml
  tags:
    - locale

- include: packages.yml
  tags:
    - packages

- import_tasks: kernel.yml
  tags:
    - kernel

- include: network.yml
  tags:
    - network

- include: filesystem.yml
  tags:
    - filesystem

- include: unattended-upgrades.yml
  tags:
    - unattended-upgrades

- include: user.yml
  tags:
    - user

- include: cgroup-killer.yml
  tags:
    - cgroup-killer

- include: nut-config.yaml
  tags:
    - nut
- include: misc-system.yml
  tags:
    - system
