apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ns.yaml
  - bazarr/ks.yaml
  - radarr/ks.yaml
  - sonarr/ks.yaml
  - sabnzbd/ks.yaml
#  - tautulli/ks.yaml
#  - tdarr/ks.yaml
  - media-index/ks.yaml
  - plex/ks.yaml
  - qbit/ks.yaml
  - qbittorrent/ks.yaml
#  - cross-seed/ks.yaml
  - unpackerr/ks.yaml
  - jellyfin/ks.yaml
#  - kyoo/ks.yaml
