---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - secret.enc.yaml
  - kapsi-bind-secret.sops.yaml
  - zerossl-secret.enc.yaml
  - zerossl-production.yaml
  - letsencrypt-production.yaml
  - letsencrypt-staging.yaml
