---
roles:
  - src: xanmanning.k3s
    version: v2.11.1
collections:
  - name: community.docker
    version: 2.0.0
  - name: community.general
    version: 3.8.0
  - name: community.kubernetes
    version: 2.0.0
  - name: community.sops
    version: 1.1.0
