---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: media
resources:
  - ./externalsecret-store.yaml
  - ./externalsecret.yaml
  - ./helm-release.yaml
  - ./pvc.yaml
commonLabels:
  app.kubernetes.io/name: plex
  app.kubernetes.io/instance: plex