apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - helm-release.yaml
  - pdns-webhook.yaml
  - pdns-secret.sops.yaml
  - letsencrypt-production.yaml
  - letsencrypt-staging.yaml
  - secret.enc.yaml
  - zerossl-production.yaml
  - zerossl-secret.enc.yaml
