---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
 - ns.yaml
 - ./autobrr/ks.yaml
 - ./prowlarr/ks.yaml
 - ./flaresolverr/ks.yaml
# - ./jellyseer/ks.yaml
# - ./maintainerr/ks.yaml
 - ./wizarr/ks.yaml
 - ./recyclarr/ks.yaml
 - ./tvheadend/ks.yaml
# - ./tdarr/ks.yaml
