apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ns.yaml
  - mariadb/ks-crds.yaml
  - mariadb/ks.yaml
#  - mariadb/ks-resources.yaml
#  - mariadb/ks-phpmyadmin.yaml
#  - mongodb/ks.yaml
  - redis/ks.yaml
  - cloudnative-pg/ks.yaml
  - cloudnative-pg/ks-cluster.yaml
  - cloudnative-pg/ks-cluster-vector.yaml
  - pgadmin/ks.yaml
  - influx/ks.yaml
